
name: Auto Assign Reviewer for frontend PRs

on:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Assign PawaraGunathilaka as a reviewer
      uses: actions/github-script@v6
      with:
        script: |
          const reviewers = ["PawaraGunathilaka"];
          const labels = context.payload.pull_request.labels.map(label => label.name.toLowerCase());
          if (labels.includes('frontend')) {
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: reviewers,
            });
          } else {
            console.log('No matching label found; skipping reviewer assignment.');
          }
  